"""Emit the manuscript's LaTeX table bodies + a plain-text claims sheet from the result JSONs.

  table_env.tex          Table 2  (test systems, generated from the network builder)
  table_multisystem.tex  all algorithms x systems
  table_benchmark_<s>.tex   per-system benchmark (unshaped return, LRR, VVR, FVR, failures, CI)
  table_fair.tex         every algorithm behind the same physics-informed mask
  table_improvement.tex  PI-MAPPO vs best baseline, with 95 % bootstrap CI of the difference
  table_csat.tex         component ablation
  table_scenarios.tex    S1-S5
  table_baselines.tex    random+mask / greedy / beam search / relaxed bound vs PI-MAPPO
  table_cost.tex         wall-clock cost
  claims.md              the sentences of the manuscript that carry numbers, re-computed

Usage:  python -m sim.make_tables [--results sim/results]
"""
from __future__ import annotations

import argparse
import json
import os

import numpy as np

from .config import load
from .networks import build, describe

HERE = os.path.dirname(os.path.abspath(__file__))
LABEL = {"dqn": "DQN", "iql": "IQL", "vdn": "VDN", "qmix": "QMIX", "ppo": "PPO", "mappo": "MAPPO",
         "pi-mappo": "PI-MAPPO", "random+mask": "Random + mask", "greedy+mask": "Greedy operator + mask",
         "beam_search": "Beam search (best known)",
         "pi-mappo-nomask": "PI-MAPPO $-$ mask/shield", "pi-mappo-nofeat": r"PI-MAPPO $-$ $\bm{\phi}^{\mathrm{PI}}$",
         "pi-mappo-noshape": "PI-MAPPO $-$ shaping", "pi-mappo-nophys": "PI-MAPPO $-$ physics loss",
         "pi-mappo-nodan": "PI-MAPPO $-$ DAN", "mappo+mask": "MAPPO + mask/shield",
         "mappo+shape": "MAPPO + shaping", "mappo+feat": r"MAPPO + $\bm{\phi}^{\mathrm{PI}}$"}
for _a in ("dqn", "iql", "vdn", "qmix", "ppo", "mappo"):
    LABEL[_a + "+pi"] = LABEL[_a] + " + PI mask"
SYSNAME = {"14": "IEEE 14-bus", "39": "IEEE 39-bus", "118": "IEEE 118-bus"}
COMP = [("feat", r"$\bm{\phi}^{\mathrm{PI}}$"), ("mask", "mask"), ("shape", "PBRS"), ("phys", r"$\mathcal{L}^{\mathrm{PI}}$"), ("dan", "DAN")]


def _load(d, fn):
    p = os.path.join(d, fn)
    return json.load(open(p)) if os.path.exists(p) else None


def ms(v, scale=1.0, fmt="{:.3f}", bold=False):
    body = f"{fmt.format(v[0] * scale)}\\pm{fmt.format(abs(v[1]) * scale).lstrip('+')}"
    return r"$\mathbf{" + body + "}$" if bold else f"${body}$"


def comps(spec):
    on = [n for k, n in COMP if spec.get(k)]
    return ", ".join(on) if on else "--"


def _hdr(caption, label, cols, star=True):
    env = "table*" if star else "table"
    return ["% Auto-generated by sim/make_tables.py -- do not edit by hand.", rf"\begin{{{env}}}[t]", r"\centering",
            rf"\caption{{{caption}}}", rf"\label{{{label}}}", r"\footnotesize", rf"\begin{{tabular}}{{{cols}}}", r"\toprule"], env


def _end(L, env):
    return "\n".join(L + [r"\bottomrule", r"\end{tabular}", rf"\end{{{env}}}"])


def table_env(cfg):
    L, env = _hdr("Test systems as built by \\texttt{sim/networks.py} (all modifications of the IEEE data are "
                  "listed in the appendix).", "tab:env_config", "lccc")
    D = {s: describe(build(s, cfg)) for s in cfg["systems"]}
    L += ["Parameter & " + " & ".join(SYSNAME[s] for s in D) + r" \\", r"\midrule"]
    rows = [("Electrical nodes", lambda d: d["buses"]), ("Lines / transformers", lambda d: f"{d['lines']} / {d['trafos']}"),
            ("Switchable branches", lambda d: d["switchable"]), ("Loads", lambda d: d["loads"]),
            ("Total load (MW / Mvar)", lambda d: f"{d['load_mw']:.4g} / {d['load_mvar']:.4g}"),
            ("Line charging (Mvar)", lambda d: f"{d['charging_mvar']:.4g}"),
            ("GFM-PV (n $\\times$ MW)", lambda d: f"{len(d['pv'])} $\\times$ {d['pv'][0]:g}"),
            ("GFM-WP (n $\\times$ MW)", lambda d: f"{len(d['wp'])} $\\times$ {d['wp'][0]:g}"),
            ("GFM-ESS (MW / MWh)", lambda d: f"{sum(d['ess_mw']):.4g} / {sum(d['ess_mwh']):.4g} ({len(d['ess_mw'])} units)"),
            ("Total GFM rating (MW / MVA)", lambda d: f"{d['ibr_mw']:.4g} / {d['ibr_mva']:.4g}"),
            ("Rated IBR MW / load MW", lambda d: f"{d['adequacy']:.3f}"),
            ("Horizon $T$ / step $\\Delta t$", lambda d: f"{cfg['time']['horizon']} / {cfg['time']['dt_min']:g} min")]
    for name, fn in rows:
        L.append(name + " & " + " & ".join(str(fn(D[s])) for s in D) + r" \\")
    return _end(L, env)


def table_multisystem(b):
    systems = [s for s in ("14", "39", "118") if s in b]
    L, env = _hdr("Held-out test performance (mean$\\pm$std over seeds): load recovery ratio, \\emph{unshaped} "
                  "episode return, voltage / frequency violation rate and share of collapsed episodes.",
                  "tab:multisystem", "l" + "ccccc" * len(systems))
    L += [" & " + " & ".join(rf"\multicolumn{{5}}{{c}}{{{SYSNAME[s]}}}" for s in systems) + r" \\",
          "Algorithm" + " & LRR & Return & VVR\\% & FVR\\% & Fail\\%" * len(systems) + r" \\", r"\midrule"]
    algos = list(b[systems[0]])
    for a in algos:
        cells = [r"\textbf{" + LABEL[a] + "}" if a == "pi-mappo" else LABEL[a]]
        for s in systems:
            m = b[s][a]["metrics"]
            best = max(b[s][x]["metrics"]["ret"][0] for x in algos)
            cells += [ms(m["lrr"]), ms(m["ret"], fmt="{:+.2f}", bold=abs(m["ret"][0] - best) < 1e-9),
                      ms(m["vvr"], 100, "{:.1f}"), ms(m["fvr"], 100, "{:.1f}"), ms(m["failed"], 100, "{:.0f}")]
        L.append(" & ".join(cells) + r" \\")
    return _end(L, env)


def table_benchmark(b, s, label, caption):
    L, env = _hdr(caption, label, "lccccccccl")
    L += [r"Algorithm & Return [95\% CI] & LRR & LRR$_w$ & Buses & VVR\% & FVR\% & Fail\% & Seeds & PI components \\", r"\midrule"]
    for a, d in b[s].items():
        m = d["metrics"]
        ci = f" [{m['ret'][2]:+.2f}, {m['ret'][3]:+.2f}]" if np.isfinite(m["ret"][2]) else ""
        L.append(" & ".join([LABEL.get(a, a), ms(m["ret"], fmt="{:+.2f}") + ci, ms(m["lrr"]), ms(m["lrr_w"]),
                             ms(m["buses"], fmt="{:.1f}"), ms(m["vvr"], 100, "{:.1f}"), ms(m["fvr"], 100, "{:.1f}"),
                             ms(m["failed"], 100, "{:.0f}"), str(m["ret"][5]), comps(d["spec"])]) + r" \\")
    return _end(L, env)


def table_improvement(b):
    systems = [s for s in ("14", "39", "118") if s in b]
    L, env = _hdr("PI-MAPPO against the best baseline (by unshaped test return) on each system; differences of "
                  "seed means with a 95\\% bootstrap interval.", "tab:improvement", "l" + "c" * len(systems), star=False)
    L += ["Metric & " + " & ".join(SYSNAME[s] for s in systems) + r" \\", r"\midrule"]
    best = {s: max((a for a in b[s] if a != "pi-mappo"), key=lambda a: b[s][a]["metrics"]["ret"][0]) for s in systems}
    L.append("Best baseline & " + " & ".join(LABEL[best[s]] for s in systems) + r" \\")

    def diff(s, k, scale=1.0, fmt="{:+.3f}"):
        x = np.array([p[k] for p in b[s]["pi-mappo"]["per_seed"]]) * scale
        y = np.array([p[k] for p in b[s][best[s]]["per_seed"]]) * scale
        rng = np.random.default_rng(0)
        bs = [rng.choice(x, len(x)).mean() - rng.choice(y, len(y)).mean() for _ in range(4000)]
        return f"${fmt.format(x.mean() - y.mean())}$ [{fmt.format(np.quantile(bs, .025))}, {fmt.format(np.quantile(bs, .975))}]"
    for name, k, sc, fmt in (("$\\Delta$ return", "ret", 1, "{:+.2f}"), ("$\\Delta$ LRR", "lrr", 1, "{:+.3f}"),
                             ("$\\Delta$ VVR (pp)", "vvr", 100, "{:+.1f}"), ("$\\Delta$ FVR (pp)", "fvr", 100, "{:+.1f}"),
                             ("$\\Delta$ collapsed episodes (pp)", "failed", 100, "{:+.0f}")):
        L.append(name + " & " + " & ".join(diff(s, k, sc, fmt) for s in systems) + r" \\")
    return _end(L, env), best


def table_rows(d, caption, label, keys=("lrr", "ret", "vvr", "fvr", "failed", "cs")):
    L, env = _hdr(caption, label, "l" + "c" * len(keys) + "cl")
    names = dict(lrr="LRR", ret="Return", vvr="VVR\\%", fvr="FVR\\%", failed="Fail\\%", cs="CS\\%")
    L += ["Variant & " + " & ".join(names[k] for k in keys) + r" & Seeds & PI components \\", r"\midrule"]
    for a, v in d.items():
        m = v["metrics"]
        cells = [ms(m[k], 100 if k in ("vvr", "fvr", "failed", "cs") else 1,
                    "{:+.2f}" if k == "ret" else ("{:.1f}" if k in ("vvr", "fvr", "failed", "cs") else "{:.3f}")) for k in keys]
        L.append(" & ".join([LABEL.get(a, a)] + cells + [str(m["ret"][5]), comps(v["spec"])]) + r" \\")
    return _end(L, env)


def table_scenarios(b, s, algos):
    L, env = _hdr(f"Scenario evaluation (Table 4) of the trained policies on the {SYSNAME[s]} system, held-out seeds.",
                  "tab:scenarios", "ll" + "c" * 5)
    L += [r"Algorithm & Scenario & LRR & Return & VVR\% & FVR\% & Fail\% \\", r"\midrule"]
    for a in algos:
        for sc_, m in b[s][a].get("scenarios", {}).items():
            L.append(" & ".join([LABEL[a], sc_, ms(m["lrr"]), ms(m["ret"], fmt="{:+.2f}"), ms(m["vvr"], 100, "{:.1f}"),
                                 ms(m["fvr"], 100, "{:.1f}"), ms(m["failed"], 100, "{:.0f}")]) + r" \\")
    return _end(L, env)


def table_baselines(bl, b):
    L, env = _hdr("Non-learning references on the held-out scenarios: what the mask alone achieves (random), a "
                  "priority-greedy operator rule, the best sequence found by beam search and a relaxed upper bound.",
                  "tab:baselines", "ll" + "c" * 4)
    L += [r"System & Policy & LRR & Return & VVR\% & FVR\% \\", r"\midrule"]
    for s, d in bl.items():
        for a in ("random+mask", "greedy+mask", "beam_search"):
            if a in d:
                m = d[a]
                L.append(" & ".join([SYSNAME[s], LABEL[a], ms(m["lrr"]), ms(m["ret"], fmt="{:+.2f}"),
                                     ms(m["vvr"], 100, "{:.1f}"), ms(m["fvr"], 100, "{:.1f}")]) + r" \\")
        if b and s in b and "pi-mappo" in b[s]:
            m = b[s]["pi-mappo"]["metrics"]
            L.append(" & ".join([SYSNAME[s], r"\textbf{PI-MAPPO}", ms(m["lrr"]), ms(m["ret"], fmt="{:+.2f}"),
                                 ms(m["vvr"], 100, "{:.1f}"), ms(m["fvr"], 100, "{:.1f}")]) + r" \\")
        L.append(f"{SYSNAME[s]} & Relaxed upper bound & ${d['upper_bound_lrr'][0]:.3f}$ & -- & -- & -- \\\\")
    return _end(L, env)


def table_cost(b, s):
    L, env = _hdr(f"Wall-clock training cost per seed on the {SYSNAME[s]} system (CPU, AC power flow in the loop).",
                  "tab:cost", "lrrr", star=False)
    L += [r"Algorithm & Episodes & s / episode & Total (s) \\", r"\midrule"]
    for a, d in b[s].items():
        L.append(f"{LABEL[a]} & {d['episodes']} & ${d['train_s'] / d['episodes']:.3f}$ & ${d['train_s']:.0f}$ \\\\")
    return _end(L, env)


def claims(b, bl, ab, meta):
    out = ["# Numbers for the manuscript text (auto-generated -- re-run after every experiment)", ""]
    if meta:
        out += [f"run label: **{meta.get('label') or 'FINAL'}**, seeds={meta['seeds']}, episodes={meta['episodes']}, "
                f"commit={meta.get('commit')}", ""]
    for s in b or {}:
        pi = b[s]["pi-mappo"]["metrics"]
        base = {a: v["metrics"] for a, v in b[s].items() if a != "pi-mappo"}
        best = max(base, key=lambda a: base[a]["ret"][0])
        out += [f"## {SYSNAME[s]}",
                f"- PI-MAPPO: LRR {100*pi['lrr'][0]:.1f} % (std {100*pi['lrr'][1]:.1f}), unshaped return {pi['ret'][0]:+.2f} "
                f"[95 % CI {pi['ret'][2]:+.2f}, {pi['ret'][3]:+.2f}], VVR {100*pi['vvr'][0]:.2f} %, FVR {100*pi['fvr'][0]:.2f} %, "
                f"collapsed episodes {100*pi['failed'][0]:.0f} %.",
                f"- best baseline by return: {LABEL[best]} (return {base[best]['ret'][0]:+.2f}, LRR {100*base[best]['lrr'][0]:.1f} %).",
                f"- relative LRR change vs MAPPO: " + (f"{100*(pi['lrr'][0]-base['mappo']['lrr'][0])/base['mappo']['lrr'][0]:+.1f} %"
                                                       if base.get('mappo') and base['mappo']['lrr'][0] > 1e-6 else
                                                       "undefined (MAPPO LRR = 0) -> report absolute difference")]
        if bl and s in bl:
            out.append(f"- random+mask LRR {100*bl[s]['random+mask']['lrr'][0]:.1f} %, greedy LRR {100*bl[s]['greedy+mask']['lrr'][0]:.1f} %, "
                       f"relaxed bound {100*bl[s]['upper_bound_lrr'][0]:.1f} %"
                       + (f", beam search {100*bl[s]['beam_search']['lrr'][0]:.1f} %" if 'beam_search' in bl[s] else "") + ".")
        out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=os.path.join(HERE, "results"))
    a = ap.parse_args()
    R = a.results
    cfg = load()
    b, fair, ab = _load(R, "benchmark.json"), _load(R, "fair.json"), _load(R, "ablation.json")
    bl, meta = _load(R, "baselines.json"), _load(R, "meta.json")
    files = {"table_env.tex": table_env(cfg)}
    if b:
        files["table_multisystem.tex"] = table_multisystem(b)
        for s in b:
            files[f"table_benchmark_{s}.tex"] = table_benchmark(
                b, s, f"tab:benchmark{s}", f"Benchmark on the modified {SYSNAME[s]} system: held-out test scenarios, "
                "mean$\\pm$std over seeds, unshaped return with 95\\% bootstrap CI.")
            files[f"table_cost_{s}.tex"] = table_cost(b, s)
        files["table_improvement.tex"], best = table_improvement(b)
        s0 = list(b)[0]
        files["table_scenarios.tex"] = table_scenarios(b, s0, [best[s0], "pi-mappo"])
    if fair:
        s0 = list(fair)[0]
        files["table_fair.tex"] = table_benchmark(fair, s0, "tab:fair", f"Fair comparison on the {SYSNAME[s0]} system: every "
                                                  "algorithm acts behind the same physics-informed mask/shield and observes $\\bm{\\phi}^{\\mathrm{PI}}$.")
    if ab:
        s0 = list(ab)[0]
        files["table_csat.tex"] = table_rows(ab[s0], f"Component ablation on the {SYSNAME[s0]} system (held-out scenarios, "
                                             "mean$\\pm$std over seeds).", "tab:csat")
    if bl:
        files["table_baselines.tex"] = table_baselines(bl, b)
    files["claims.md"] = claims(b, bl, ab, meta)
    for fn, txt in files.items():
        with open(os.path.join(R, fn), "w") as f:
            f.write(txt + "\n")
        print("wrote", os.path.join(R, fn))


if __name__ == "__main__":
    main()
